config/routes.rb
Rails.application.routes.draw do


  get 'avatars/create'
  get 'users/show'
  #get 'events/new'

  devise_for :users






  root to: 'events#index'
  #resources :users, only: [:show]



  resources :users, only: [:show] do
    resources :avatars, only: [:create]

    end


    resources :events do
      resources :avatars, only: [:create]

    end
    resources :charges


  resources :participations


  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	belongs_to :event
	belongs_to :participant, class_name: "User"

	
	after_create :sent_email_to_admin
		def sent_email_to_admin
			UserMailer.email_for_admin(self).deliver_now
		end

end

app/models/event.rb
class Event < ApplicationRecord
	require'date'
	has_many :attendances
	has_many :users , through: :attendances
    belongs_to :admin, class_name: "User"

		has_one_attached :avatar

	#validates :start_date, presence: true
	#validates :duration, presence: true, numericality: {:greater_than_or_equal_to => 0}
	#validates :title, presence: true, length: { in: 5..140 }
	#validates :description, presence: true, length: { in: 20..1000}
	#validates :price, presence: true, length: { in: 1..1000}
	#validates :location, presence: true


#start_date must be in the future
	#validate :start_date_cannot_be_in_the_past
  #  def start_date_cannot_be_in_the_past
  #      if start_date < Date.today
  #          errors.add(:start_date, "can't be in the past")
  #      end
  #  end
#duration must be multiple of 5
  #  validate :duration_is_multiple_by_five
    #def duration_is_multiple_by_five
    #    if (duration.to_i%5  != 0)
  #          errors.add(:duration, "put value multiple by 5")
  #      end
  #  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
#Jointure
	has_many :attendances
	has_many :events, through: :attendances
#ActionMailer
	after_create :welcome_send

		def welcome_send
			UserMailer.welcome_email(self).deliver_now
		end


    has_one_attached :avatar

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  before_action :configure_devise_parameters, if: :devise_controller?

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name,:description, :is_alive, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name,:description, :is_alive, :email, :password, :password_confirmation)}
  end




end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  def create

    @user = User.find(params[:user_id])
    @user.avatar.attach(params[:avatar])
    redirect_to(user_path(@user))

  end


  def create

    @event = Event.find(params[:event_id])
    @event.avatar.attach(params[:avatar])
    redirect_to(event_path(@event))

  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new

  end

  def create
    # Amount in cents




      @amount = 500

      customer = Stripe::Customer.create({email: params[:stripeEmail],source: params[:stripeToken],
        })

  charge = Stripe::Charge.create({
    customer: customer.id,amount: @amount,description: 'Rails Stripe customer',currency: 'USD',
  })

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index

    @event = Event.all

  end

  def new

    @event = Event.new

  end


  def show

    @event = Event.find(params[:id])



  end


  def create




    @event = Event.create(start_date:params[:start_date],duration:params[:duration],title:params[:title],description:params[:description],price:params[:price],
      location:params[:location],admin_id:current_user.id)
    if @event.save
      redirect_to "/"
    end
    #@event = Event.create(event_params)




    # POURQUOI ça MARCHE sans ce TRUC?????


    #@event = Event.find(params[:event_id])
    #@event.avatar.attach(params[:avatar])
    #redirect_to(event_path(@event))

  end

#private
 #def event_params
  #params.require(:event).permit(:start_date)
 #end




before_action :authenticate_user!, only: [:index, :new]
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def create
    @event =  Event.find(params[:id])
    # Amount in cents
      #@amount = @event        #500

      customer = Stripe::Customer.create({email: params[:stripeEmail],source: params[:stripeToken],
        })

  charge = Stripe::Charge.create({
    customer: customer.id,amount: @event,description: 'Rails Stripe customer',currency: 'eur',
  })

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show

  #@user = User.find(params[:id])
    #@user = User.find(session[:user_id])
    #@user.users_id = User.find(params[:users_id]).id
    #@user ||= User.find(session[:user_id])


   params[:id].to_i == current_user.id
  #else
    #redirect_to user_session_path(current_user.id)

    #@user = User.find(params[:id])  # Active Storage

  end

  before_action :authenticate_user!, only: [:show]

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/avatars/create.html.erb
<h1>Avatars#create</h1>
<p>Find me in app/views/avatars/create.html.erb</p>

app/views/charges/create.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <h2>Thanks, you paid <strong>5 EURO</strong>!</h2>

  </body>
</html>

app/views/charges/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <%= form_tag "/events/:event_id/charges" do %>
    <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount:<%@event.price %>€</span>
    </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="PAIEMENT ONLINE!"
          data-amount= "<%=@event.price %>"
          data-currency= "eur"
          data-locale="auto"></script></br>

          <% end %>

  </body>
</html>

app/views/events/index.html.erb
<html>
</br>
<h1 class="text-success"><center>Les EVENEMENTS</center></h1>
<% @event.each do |event| %>
  <p class="text-primary"> <b>Titre:</b>
    <%= event.title %></p>

  <p>Description:</p>
  <%= event.description %> </br></br>

  <p>Location:
    <%= event.location %> </p>

  <p>Prix:
    <%= event.price %> €</p>





    <input  class = "btn btn-primary btn-lg" type ="button" value="Show" onclick="document.location.href='<%= event_path(event.id)%>';" style="background-color: lime">




    <%= form_tag charges_path do %>
    <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>

    <label class="amount">
      <span>Amount:<%=event.price %>€</span>
    </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="PAIEMENT ONLINE!"
          data-amount= "<%=event.price.to_i*100%>"
          data-currency= "eur"
          data-locale="auto"></script></br>

          <% end %>
<% end %>

</html>

<p>Find me in app/views/events/index.html.erb</p>

app/views/events/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>

  <style media="screen">

  form
    {
      /* Uniquement centrer le formulaire sur la page */
        margin: 5;
        width: 400px;
          /* Encadré pour voir les limites du formulaire */
            padding: 1em;
            border: 0px solid #CCC;
            border-radius: 1em;

          }

          button {
    /* Pour placer le bouton à la même position que les champs texte */
    padding-left: 60px; /* même taille que les étiquettes */
    padding-right: 57px;
  }

  button {
    /* Cette marge supplémentaire représente grosso modo le même espace que celui
       entre les étiquettes et les champs texte */
    margin-left: 3em;

  }

  </style>

  <body>
<br />
<h1><center>CREATION EVENTS HERE...</center></h1>

<%= form_tag url_for(action: 'create'), method: "post" do %>


    <%= label_tag 'start_date: (day-month-year)' %></br>
    <%= text_field_tag'start_date', @event.start_date %>
    <br /> <br />




  <%= label_tag 'duration: (day)' %></br>
  <%= text_field_tag 'duration', @event.duration %>
  <br /> <br />

  <%= label_tag 'title:' %></br>
  <%= text_field_tag 'title', @event.title %>
  <br /> <br />

  <%= label_tag 'description:' %></br>
  <%= text_area_tag 'description', @event.description %>
  <br /> <br />

  <%= label_tag 'price:' %></br>
  <%= text_field_tag 'price', @event.price %>
  <br /> <br />

  <%= label_tag 'location:' %></br>
  <%= text_field_tag 'location', @event.location %>
  <br /> <br />

  <%= submit_tag "Create Event" %>

<%end%>

  </body>
</html>

<!--
    <%= simple_form_for :event, url: :events, method: :post do |f| %>
<div class="container">
 <div class="row">
  <div class='col-sm-6 col-sm-offset-3'>
   <div class="form-group">
    <div class='input-group date' id='datetimepicker'>
    <%= f.input :start_date, label: false, placeholder: "Sélectionnez la date et l'heure", class: "form-control" %>
     <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
     </div>
    </div>

  </div>
 </div>
</div>
<% end %>
-->

app/views/events/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>





  <body>
    <h1><center>SHOW EVENT...</center></h1>



    <p>Start_date :
    <%=@event.start_date%></p>

    <p>Duration :
    <%=@event.duration%> JOURS</p>

    <p>Titre :
    <%=@event.title%></br></p>

    <p>Description:</p>
    <%=@event.description%> </br></br>

    <p>Price :
    <%=@event.price%> €</p>

    <p>Location :
    <%=@event.location%></p></br>

    <p>Admin :
    <%=@event.admin.first_name%></p>





    <h1><center>PHOTO</center></h1>

<!--<p>Bienvenue sur la page d'ajout d'un avatar pour le User portant l'id : <%=@event.id%></p>
<h3>Avatar actuel</h3>-->

<center>
<%if @event.avatar.attached?%>
  <%= image_tag @event.avatar, alt: 'avatar'%>
<%else%>
  <!--<p>=== Il n'y a pas encore d'avatar lié à cet utilisateur ===</p>-->
<%end%>

</br></br></br>

    <h3>Mettre à jour ?</h3>
<%= form_tag event_avatars_path(@event), multipart: true do %>
  <%= file_field_tag :avatar %>
  <%= submit_tag "mettre à jour" %>
<% end %>
</center>


  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheEventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">ACCEUILLE<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/events/new">CREER events</a>
      </li>

      <%if !current_user%>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="sign_up" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Connexion
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/users/sign_up">S'inscrire</a>
          <a class="dropdown-item" href="/users/sign_in">Se connecter</a>


          <%else%>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="sign_up" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              PROFIL
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="/users/show">Mon Profil</a>

              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="/users/sign_out">DECONNECT</a>

        </div>

        <%end%>

      </li>

<!--
      <li class="nav-item">
        <a class="nav-link " href="#">PROFIL</a>
      </li>
    -->
    </ul>

    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <%= yield %>
  </body>
</html>

app/views/participations/edit.html.erb
<h1>Participations#edit</h1>
<p>Find me in app/views/participations/edit.html.erb</p>

app/views/participations/index.html.erb
<h1>Participations#index</h1>
<p>Find me in app/views/participations/index.html.erb</p>

app/views/participations/new.html.erb
<h1>Participations#new</h1>
<p>Find me in app/views/participations/new.html.erb</p>


    

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <h1><center>YOUR PROFIL...</center></h1>


    <p> WELCOM
    <%=current_user.first_name%> <%=current_user.last_name%></p></br>

      <p>What about YOU:</p>
       <%=current_user.description%></br></br>

       <p>Your mail Adress:
       <%=current_user.email%></p>



            <h1><center>Photo Profil</center></h1>

          <!--  <p>Bienvenue sur la page d'ajout d'un avatar pour le User portant l'id : <%=@current_user.id%></p>
            <h3>Avatar actuel</h3> -->


            <center>
              <%if @current_user.avatar.attached?%>
              <%= image_tag @current_user.avatar, alt: 'avatar' %>
              <%else%>
              <p>=== Il n'y a pas encore d'avatar lié à cet utilisateur ===</p>
              <%end%>

            </center>

</br></br></br>
              <h3>Changer photo ?</h3>
<%= form_tag user_avatars_path(@current_user), multipart: true do %>
  <%= file_field_tag :avatar %>
  <%= submit_tag "mettre à jour" %>
<% end %>


  </body>
</html>

<p>Find me in app/views/users/show.html.erb</p>